### PR TITLE
Build h5py against Cython < 3.0 in CI

### PR DESCRIPTION
**Pull request by paulromano**
# Description

Some of you may have noticed that recent CI jobs are failing. It looks like this is due to a new release of Cython (3.0), which appears to be incompatible with the most recent release of h5py (see h5py/h5py#2268). This PR restricts the Cython version used to build h5py to get around that.

# Checklist

- [x] I have performed a self-review of my own code
- [x] <s>I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) on any C++ source files (if applicable)</s>
- [x] <s>I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)</s>
- [x] <s>I have made corresponding changes to the documentation (if applicable)</s>
- [x] <s>I have added tests that prove my fix is effective or that my feature works (if applicable)</s>

### CODE REVIEW

**Comment by paulromano** [comment]
@shimwell Hopefully not since we're not doing anything super exotic in OpenMC with Cython, but we'll find out shortly when CI runs complete

**Comment by gridley** [comment]
This is a bummer because the newer cython version is required to circumvent a compile error that prevents it from working with python 3.11. Details below.


```
openmc/data/_endf.c: In function ‘__Pyx_AddTraceback’:
openmc/data/_endf.c:456:62: error: invalid use of incomplete typedef ‘PyFrameObject’ {aka ‘struct _frame’}
  456 |   #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
      |                                                              ^~
openmc/data/_endf.c:1903:5: note: in expansion of macro ‘__Pyx_PyFrame_SetLineNumber’
 1903 |     __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
error: command '/usr/bin/gcc' failed with exit code 1
gpad%

```

This has been encountered elsewhere and is apparently fixed in newer cython versions.

https://github.com/yaml/pyyaml/issues/630


What do you all think of dropping cython altogether? The small amount of cython code could be translated to C++ with ease and made callable in openmc.lib. This might be a good task for an undergrad to get warmed up to coding with.

I say this because Cython is a complicated dependency, whereas ctypes is rock solid.

**Comment by shimwell** [comment]
I like that idea @gridley I think dropping cython would also help make openmc pip installable and in general keeping the dependency stack small is just good all around

**Comment by paulromano** [comment]
@gridley Cython is a build-time dependency. Note that this PR does _not_ change the Cython version in our pyproject.toml, so in principle, you should still be able to build OpenMC against the newer Cython even if you have an h5py installation that was built against an older Cython.
