### ISSUE TITLE
openmc: Fails to compile with fmt 11.2.0

### ISSUE THREAD

**Issue by yurivict** [openmc-dev/openmc#3410]
## Bug Description
```
[ 27%] Building CXX object CMakeFiles/libopenmc.dir/src/mgxs.cpp.o
/usr/local/bin/mpic++ -DBUILD_TYPE=Release -DCOMPILER_ID=Clang -DCOMPILER_VERSION=18.1.6 -DFMT_SHARED -DGSL_THROW_ON_CONTRACT_VIOLATION -DH5_BUILT_AS_DYNAMIC_LIB -DUSE_LIBPNG -Dgsl_CONFIG_ALLOWS_NONSTRICT_SPAN_COMPARISON=1 -Dgsl_CONFIG_DEFAULTS_VERSION=1 -Dlibopenmc_EXPORTS -I/wrkdirs/usr/ports/science/openmc/work/openmc-0.15.0/include -I/wrkdirs/usr/ports/science/openmc/work/.build/include -I/wrkdirs/usr/ports/science/openmc/work/openmc-0.15.0/vendor/gsl-lite/include -O2 -pipe -march=znver4 -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -march=znver4 -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG -std=c++17 -fPIC -DH5Oget_info_by_idx_vers=1 -DH5O_info_t_vers=1 -fopenmp=libomp -MD -MT CMakeFiles/libopenmc.dir/src/mgxs.cpp.o -MF CMakeFiles/libopenmc.dir/src/mgxs.cpp.o.d -o CMakeFiles/libopenmc.dir/src/mgxs.cpp.o -c /wrkdirs/usr/ports/science/openmc/work/openmc-0.15.0/src/mgxs.cpp
--- CMakeFiles/libopenmc.dir/src/geometry.cpp.o ---
In file included from /wrkdirs/usr/ports/science/openmc/work/openmc-0.15.0/src/geometry.cpp:3:
In file included from /usr/local/include/fmt/core.h:5:
In file included from /usr/local/include/fmt/format.h:41:
/usr/local/include/fmt/base.h:2275:23: error: no matching member function for call to 'format'
 2275 |     ctx.advance_to(cf.format(*static_cast<qualified_type*>(arg), ctx));
      |                    ~~~^~~~~~
```

## Environment
FreeBSD 14.2
Version: 0.15.0

**Comment by GuySten** [comment]
Fixed by #3172
